### ISSUE TITLE
Warning: An error occurred while requesting the API

### ISSUE THREAD

**Issue by mariushosting** [naskio/docker-strapi#7]
@naskio Can't access serverip:1337/admin because I receive Warning: An error occurred while requesting the API

:latest tag 4.5.0

**Comment by mariushosting** [comment]
![api error](https://user-images.githubusercontent.com/37554361/201263439-d4fc3a6e-76ea-46a8-a044-00778833595a.png)
![api2](https://user-images.githubusercontent.com/37554361/201263578-91cd4891-f236-4d95-90d6-4cf2b97ca605.png)

**Comment by NebojsaKrtolica** [comment]
Hi @mariushosting 

I had the same error, long story short:

1. exec into the strapi container : run `docker exec -it <container-id> bash`
2. due to magic currently unclear to me, strapi needs a rebuild, so run : `yarn build`
3. kill all node processes (this will kill the container, but since it will persist the yarn build changes, all is well) with `pkill node`

After a while(= successful start of the strapi container), the /admin shouldn't throw that error anymore.

I hope this helps 🍀

**Comment by mariushosting** [comment]
> Hi @mariushosting
> 
> I had the same error, long story short:
> 
> 1. exec into the strapi container : run `docker exec -it <container-id> bash`
> 2. due to magic currently unclear to me, strapi needs a rebuild, so run : `yarn build`
> 3. kill all node processes (this will kill the container, but since it will persist the yarn build changes, all is well) with `pkill node`
> 
> After a while(= successful start of the strapi container), the /admin shouldn't throw that error anymore.
> 
> I hope this helps 🍀
> 
> P.S. To be completely transparent, I have set up SSL for that container too, and I cannot confirm if that contributed to the solution or not, but after the abovementioned steps it worked for me. GL

Hello I already solved the issue here: https://mariushosting.com/how-to-install-strapi-on-your-synology-nas/ using 
**npm run build**
